// <auto-generated />
using HotelListing.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HotelListing.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("HotelListing.Domain.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Albania",
                            ShortName = "AL"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Germany",
                            ShortName = "DU"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Italy",
                            ShortName = "IT"
                        },
                        new
                        {
                            Id = 4,
                            Name = "England",
                            ShortName = "EN"
                        });
                });

            modelBuilder.Entity("HotelListing.Domain.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Adrsess")
                        .HasColumnType("text");

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Adrsess = "Hotel 1 street",
                            CountryId = 1,
                            Name = "Hotel 1",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 2,
                            Adrsess = "Hotel 2 street",
                            CountryId = 2,
                            Name = "Hotel 2",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 3,
                            Adrsess = "Hotel 3 street",
                            CountryId = 3,
                            Name = "Hotel 3",
                            Rating = 4.7999999999999998
                        },
                        new
                        {
                            Id = 4,
                            Adrsess = "Hotel 4 street",
                            CountryId = 4,
                            Name = "Hotel 4",
                            Rating = 4.7999999999999998
                        });
                });

            modelBuilder.Entity("HotelListing.Domain.Hotel", b =>
                {
                    b.HasOne("HotelListing.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });
#pragma warning restore 612, 618
        }
    }
}
